from typing import Annotated
from typing_extensions import NotRequired, TypedDict
from langgraph.graph import MessagesState


def _merge_debate_state(left: dict | None, right: dict | None) -> dict:
    """Reducer for debate states when parallel graph paths converge.

    Debate nodes return the full nested state, not a small patch. In normal
    sequential debate flow, the state with the higher ``count`` is the newer
    one. If two paths write the same count in the same superstep, merge fields
    so manager decisions/judge fields are not dropped while avoiding LangGraph's
    default single-writer restriction.
    """
    if not left:
        return dict(right or {})
    if not right:
        return dict(left)

    left_count = int(left.get("count") or 0)
    right_count = int(right.get("count") or 0)
    if right_count > left_count:
        return dict(right)
    if left_count > right_count:
        return dict(left)
    return {**left, **right}


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    hot_money_report: Annotated[str, "Report from the Hot Money Analyst"]
    policy_report: Annotated[str, "Report from the Policy Analyst"]
    lockup_report: Annotated[str, "Report from the Lockup Analyst"]
    kronos_report: Annotated[str, "Report from the Kronos-style scenario analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState,
        "Current state of the debate on if to invest or not",
        _merge_debate_state,
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState,
        "Current state of the debate on evaluating risk",
        _merge_debate_state,
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    execution_context: NotRequired[str]
    live_quote_at_run_json: NotRequired[str]

    # Standardized dimensions snapshot (after analysts, before bull/bear debate)
    dimensions_summary: NotRequired[str]
    dimensions_error: NotRequired[str]
    dimensions_snapshot_json: NotRequired[str]

    overnight_signal: NotRequired[str]
    alt_data_report: NotRequired[str]
    options_recommendation: NotRequired[str]
    options_chain_snapshot: NotRequired[dict]
